### ISSUE TITLE
Last code change not updated?

### ISSUE THREAD

**Issue by Bmacuser1** [ColorlibHQ/Fashe#24] opened 2019-03-21 08:20 UTC
Hi guys

the ticket #20 has been closed but the last version to download still has the old code. Did i miss something here? Just installed the theme fresh again and cant see any changes. as mentioned in my last comment the last code change was before your last change

Cheers
Björn

**Comment by cristianraiber** [comment] 2019-03-21 10:54
@Bmacuser1 - where did you download the latest theme from?

**Comment by Bmacuser1** [comment] 2019-03-21 11:31
Here from github download button :)

Raiber Cristian <notifications@github.com> schrieb am Do., 21. März 2019,
17:54:

**Comment by dvd84** [comment] 2019-03-25 01:08
I am having the same issues as Bjorn on that last ticket, but I have downloaded the latest code and it doesn't seem to be fixed there, the cart is still not updating properly. Can you please advise?

**Comment by cristianraiber** [comment] 2019-03-25 06:43
@cristian-e - can you please check this?

**Comment by cboursier** [comment] 2019-03-26 12:07
@dvd84 @Bmacuser1  Hello, i maybe can help you. I had the same problem and fixed it by manualy searching the cart.liquid code from the github file and change it on my site. It seems that the last version do not include last fixs.

**Comment by hadasabi** [comment] 2019-03-29 20:20
i am also still having cart issues

> @dvd84 @Bmacuser1 Hello, i maybe can help you. I had the same problem and fixed it by manualy searching the cart.liquid code from the github file and change it on my site. It seems that the last version do not include last fixs.

please share with us. i am facing the same problems

**Comment by cristian-e** [comment] 2019-04-01 07:03
> @dvd84 @Bmacuser1 Hello, i maybe can help you. I had the same problem and fixed it by manualy searching the cart.liquid code from the github file and change it on my site. It seems that the last version do not include last fixs.

Yes, you can also search and replace the changed files manually. The files that have been recently changed in the latest fix are:
`assets/common.js.liquid`
`assets/common.js`
`assets/main.css`
`assets/main.css.liquid`
`config/settings_schema.json`
`config/settings_data.json`
`layout/theme.liquid`
`locales/en.default.json`
`locales/fr.json`
`sections/instagram-feed.liquid`
`snippets/footer-1.liquid`
`snippets/header-1.liquid`
`snippets/header-2.liquid`
`snippets/header-3.liquid`
`snippets/header-cart-mob.liquid`
`snippets/header-cart.liquid`
`snippets/product-grid-item-deal.liquid`
`snippets/product-grid-item.liquid`
`snippets/search-result-grid.liquid`
`templates/cart.liquid`
`templates/customers/account.liquid`.

Also you can try downloading the theme from here and see if this helps:
https://github.com/MachoThemes/Fashe.

They are basically the same theme.

**Comment by hadasabi** [comment] 2019-04-01 08:54
> > @dvd84 @Bmacuser1 Hello, i maybe can help you. I had the same problem and fixed it by manualy searching the cart.liquid code from the github file and change it on my site. It seems that the last version do not include last fixs.
> 
> Yes, you can also search and replace the changed files manually. The files that have been recently changed in the latest fix are:
> `assets/common.js.liquid`
> `assets/common.js`
> `assets/main.css`
> `assets/main.css.liquid`
> `config/settings_schema.json`
> `config/settings_data.json`
> `layout/theme.liquid`
> `locales/en.default.json`
> `locales/fr.json`
> `sections/instagram-feed.liquid`
> `snippets/footer-1.liquid`
> `snippets/header-1.liquid`
> `snippets/header-2.liquid`
> `snippets/header-3.liquid`
> `snippets/header-cart-mob.liquid`
> `snippets/header-cart.liquid`
> `snippets/product-grid-item-deal.liquid`
> `snippets/product-grid-item.liquid`
> `snippets/search-result-grid.liquid`
> `templates/cart.liquid`
> `templates/customers/account.liquid`.
> 
> Also you can try downloading the theme from here and see if this helps:
> https://github.com/MachoThemes/Fashe.
> 
> They are basically the same theme.

Hi Christian, i just downloaded the theme again from your link and the issues are not still not fixed. my preview of cart on mobile from top bar is still showing up on the left and is a little "cut off". I also still need to refresh the page to apply any changes to the cart itself.  please advise. i would love to launch my site this week with your theme.
thank you :)

**Comment by cristian-e** [comment] 2019-04-04 12:22
> Hi Christian, i just downloaded the theme again from your link and the issues are not still not fixed. my preview of cart on mobile from top bar is still showing up on the left and is a little "cut off". I also still need to refresh the page to apply any changes to the cart itself. please advise. i would love to launch my site this week with your theme.
> thank you :)

The cart positioning and behavior should be like in this example:
https://christian-gabriel1015-store.myshopify.com/
Notice the positioning on mobile and that the shopping cart gets updated correctly when adding products.

The only reason I can think of, for the cart not working properly is some sort of javascript error.

**Comment by hadasabi** [comment] 2019-04-07 09:11
Hi Christian, i'm not sure i understood your response. my theme had no changes in the cart code and i do not see the mobile version in your link. what should i do, download the new version again? how can i fix this issue of cart not updating on mobile?
thank you

**Comment by Symsys** [comment] 2019-08-08 06:51
> > Hi Christian, i just downloaded the theme again from your link and the issues are not still not fixed. my preview of cart on mobile from top bar is still showing up on the left and is a little "cut off". I also still need to refresh the page to apply any changes to the cart itself. please advise. i would love to launch my site this week with your theme.
> > thank you :)
> 
> The cart positioning and behavior should be like in this example:
> https://christian-gabriel1015-store.myshopify.com/
> Notice the positioning on mobile and that the shopping cart gets updated correctly when adding products.
> 
> The only reason I can think of, for the cart not working properly is some sort of javascript error.

Hi,
I tried downloading the resource from github but the issue is the same. However, the issue seems to be fixed in the link https://christian-gabriel1015-store.myshopify.com you shared.
Would it be possible for you to download the theme directly from the store and send it to me?

**Comment by Symsys** [comment] 2019-08-21 11:01
> > > Hi Christian, i just downloaded the theme again from your link and the issues are not still not fixed. my preview of cart on mobile from top bar is still showing up on the left and is a little "cut off". I also still need to refresh the page to apply any changes to the cart itself. please advise. i would love to launch my site this week with your theme.
> > > thank you :)
> > 
> > 
> > The cart positioning and behavior should be like in this example:
> > https://christian-gabriel1015-store.myshopify.com/
> > Notice the positioning on mobile and that the shopping cart gets updated correctly when adding products.
> > The only reason I can think of, for the cart not working properly is some sort of javascript error.
> 
> Hi,
> I tried downloading the resource from github but the issue is the same. However, the issue seems to be fixed in the link https://christian-gabriel1015-store.myshopify.com you shared.
> Would it be possible for you to download the theme directly from the store and send it to me?

@cristian-e Can you please look into this?

**Closed** 2019-10-16 18:42 UTC
